import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Script from "next/script";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* 
          -- One way to handle script --
          <script
            defer
            type="text/javascript"
            src="https://assets.platform.bytandym.com/custom-mapps-assets/tandym-mapps-custom-v1.js?tandym_api_key=185c732e-02f0-4b01-bd57-812d70992a62-42485d6c-c010-42a0-bbc3-bfc650acc791-1689284239728"
          ></script>
        */}
      </Head>

      {/* 
        -- Second way to handle the script:  Carefull, this NextJS <Script /> component must be OUTSIDE <Head></Head> -- 
      */}
      <Script
        src="https://assets.platform.bytandym.com/custom-mapps-assets/tandym-mapps-custom-v1.js?tandym_api_key=185c732e-02f0-4b01-bd57-812d70992a62-42485d6c-c010-42a0-bbc3-bfc650acc791-1689284239728"
        strategy="lazyOnload"
        onLoad={() => console.log("loaded")}
        onError={() => console.log("error")}
      />
      <main className={styles.main}>
        <div>
          <h1>TESTING MAPPS</h1>
          <div>
            {/* Here is the mapps web component */}
            <tandym-mapps
              data-tandym-widget="PDP"
              data-tandym-product-price="5620"
            ></tandym-mapps>
          </div>
        </div>
      </main>
    </>
  );
}
